\hypertarget{classdg_1_1deepcore_1_1_async_error}{}\section{dg\+:\+:deepcore\+:\+:Async\+Error Class Reference}
\label{classdg_1_1deepcore_1_1_async_error}\index{dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}}


\subsection{Detailed Description}
Base class for asynchronous processes that need to report an error from another thread. 

{\ttfamily \#include $<$utility/\+Async\+Error.\+h$>$}

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
std\+::exception\+\_\+ptr \hyperlink{classdg_1_1deepcore_1_1_async_error_a354a3ed3bdb3b9084602fc2ce2028478}{error} () const 
\begin{DoxyCompactList}\small\item\em Gets the error, if one was set by a worker thread. \end{DoxyCompactList}\item 
void \hyperlink{classdg_1_1deepcore_1_1_async_error_a4a111596085600b017485d15078760eb}{rethrow\+If\+Error} () const 
\begin{DoxyCompactList}\small\item\em If an error was set, rethrow the exception. \end{DoxyCompactList}\item 
void \hyperlink{classdg_1_1deepcore_1_1_async_error_aa71c047173cec3f535d24f67599d9a18}{set\+On\+Error} (\hyperlink{group___utility_module_ga21a199c126b87ba8bfe8ad7952dbaf3b}{On\+Error\+Func} func)
\begin{DoxyCompactList}\small\item\em Sets the on error callback. \end{DoxyCompactList}\end{DoxyCompactItemize}
\subsection*{Protected Member Functions}
\begin{DoxyCompactItemize}
\item 
void \hyperlink{classdg_1_1deepcore_1_1_async_error_a110fc34acc63e4eaa95fab542fa2d622}{call\+On\+Error} () const 
\begin{DoxyCompactList}\small\item\em Calls the on error callback. \end{DoxyCompactList}\item 
void \hyperlink{classdg_1_1deepcore_1_1_async_error_a8cc565e1f74ae9d7cea234dde3154a5b}{set\+And\+Call\+On\+Error} ()
\begin{DoxyCompactList}\small\item\em Sets the currently called exception as error and calls the on error callback. \end{DoxyCompactList}\item 
void \hyperlink{classdg_1_1deepcore_1_1_async_error_a02732133e16f3e573f1b6eb971d95bdc}{set\+Error} (const std\+::exception\+\_\+ptr \&\hyperlink{classdg_1_1deepcore_1_1_async_error_a354a3ed3bdb3b9084602fc2ce2028478}{error})
\begin{DoxyCompactList}\small\item\em Sets the error set by a worker thread. \end{DoxyCompactList}\item 
void \hyperlink{classdg_1_1deepcore_1_1_async_error_afe76c579587f5c6a2255257b9a624c4b}{set\+Error} ()
\begin{DoxyCompactList}\small\item\em Sets the currently caught exception as the error. \end{DoxyCompactList}\end{DoxyCompactItemize}


\subsection{Member Function Documentation}
\index{dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}!call\+On\+Error@{call\+On\+Error}}
\index{call\+On\+Error@{call\+On\+Error}!dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}}
\subsubsection[{\texorpdfstring{call\+On\+Error() const }{callOnError() const }}]{\setlength{\rightskip}{0pt plus 5cm}void dg\+::deepcore\+::\+Async\+Error\+::call\+On\+Error (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
) const\hspace{0.3cm}{\ttfamily [protected]}}\hypertarget{classdg_1_1deepcore_1_1_async_error_a110fc34acc63e4eaa95fab542fa2d622}{}\label{classdg_1_1deepcore_1_1_async_error_a110fc34acc63e4eaa95fab542fa2d622}


Calls the on error callback. 

\index{dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}!error@{error}}
\index{error@{error}!dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}}
\subsubsection[{\texorpdfstring{error() const }{error() const }}]{\setlength{\rightskip}{0pt plus 5cm}std\+::exception\+\_\+ptr dg\+::deepcore\+::\+Async\+Error\+::error (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
) const}\hypertarget{classdg_1_1deepcore_1_1_async_error_a354a3ed3bdb3b9084602fc2ce2028478}{}\label{classdg_1_1deepcore_1_1_async_error_a354a3ed3bdb3b9084602fc2ce2028478}


Gets the error, if one was set by a worker thread. 

\begin{DoxyReturn}{Returns}
The error. 
\end{DoxyReturn}
\index{dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}!rethrow\+If\+Error@{rethrow\+If\+Error}}
\index{rethrow\+If\+Error@{rethrow\+If\+Error}!dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}}
\subsubsection[{\texorpdfstring{rethrow\+If\+Error() const }{rethrowIfError() const }}]{\setlength{\rightskip}{0pt plus 5cm}void dg\+::deepcore\+::\+Async\+Error\+::rethrow\+If\+Error (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
) const}\hypertarget{classdg_1_1deepcore_1_1_async_error_a4a111596085600b017485d15078760eb}{}\label{classdg_1_1deepcore_1_1_async_error_a4a111596085600b017485d15078760eb}


If an error was set, rethrow the exception. 

\index{dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}!set\+And\+Call\+On\+Error@{set\+And\+Call\+On\+Error}}
\index{set\+And\+Call\+On\+Error@{set\+And\+Call\+On\+Error}!dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}}
\subsubsection[{\texorpdfstring{set\+And\+Call\+On\+Error()}{setAndCallOnError()}}]{\setlength{\rightskip}{0pt plus 5cm}void dg\+::deepcore\+::\+Async\+Error\+::set\+And\+Call\+On\+Error (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)\hspace{0.3cm}{\ttfamily [protected]}}\hypertarget{classdg_1_1deepcore_1_1_async_error_a8cc565e1f74ae9d7cea234dde3154a5b}{}\label{classdg_1_1deepcore_1_1_async_error_a8cc565e1f74ae9d7cea234dde3154a5b}


Sets the currently called exception as error and calls the on error callback. 

\index{dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}!set\+Error@{set\+Error}}
\index{set\+Error@{set\+Error}!dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}}
\subsubsection[{\texorpdfstring{set\+Error(const std\+::exception\+\_\+ptr \&error)}{setError(const std::exception_ptr &error)}}]{\setlength{\rightskip}{0pt plus 5cm}void dg\+::deepcore\+::\+Async\+Error\+::set\+Error (
\begin{DoxyParamCaption}
\item[{const std\+::exception\+\_\+ptr \&}]{error}
\end{DoxyParamCaption}
)\hspace{0.3cm}{\ttfamily [protected]}}\hypertarget{classdg_1_1deepcore_1_1_async_error_a02732133e16f3e573f1b6eb971d95bdc}{}\label{classdg_1_1deepcore_1_1_async_error_a02732133e16f3e573f1b6eb971d95bdc}


Sets the error set by a worker thread. 


\begin{DoxyParams}[1]{Parameters}
\mbox{\tt in}  & {\em error} & The error. \\
\hline
\end{DoxyParams}
\index{dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}!set\+Error@{set\+Error}}
\index{set\+Error@{set\+Error}!dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}}
\subsubsection[{\texorpdfstring{set\+Error()}{setError()}}]{\setlength{\rightskip}{0pt plus 5cm}void dg\+::deepcore\+::\+Async\+Error\+::set\+Error (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)\hspace{0.3cm}{\ttfamily [protected]}}\hypertarget{classdg_1_1deepcore_1_1_async_error_afe76c579587f5c6a2255257b9a624c4b}{}\label{classdg_1_1deepcore_1_1_async_error_afe76c579587f5c6a2255257b9a624c4b}


Sets the currently caught exception as the error. 

\index{dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}!set\+On\+Error@{set\+On\+Error}}
\index{set\+On\+Error@{set\+On\+Error}!dg\+::deepcore\+::\+Async\+Error@{dg\+::deepcore\+::\+Async\+Error}}
\subsubsection[{\texorpdfstring{set\+On\+Error(\+On\+Error\+Func func)}{setOnError(OnErrorFunc func)}}]{\setlength{\rightskip}{0pt plus 5cm}void dg\+::deepcore\+::\+Async\+Error\+::set\+On\+Error (
\begin{DoxyParamCaption}
\item[{{\bf On\+Error\+Func}}]{func}
\end{DoxyParamCaption}
)}\hypertarget{classdg_1_1deepcore_1_1_async_error_aa71c047173cec3f535d24f67599d9a18}{}\label{classdg_1_1deepcore_1_1_async_error_aa71c047173cec3f535d24f67599d9a18}


Sets the on error callback. 


\begin{DoxyParams}[1]{Parameters}
\mbox{\tt in}  & {\em func} & The on error callback. \\
\hline
\end{DoxyParams}
